name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build script
        run: echo "Building the project..."

  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build  # test depends on build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running tests..."

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: test  # deploy depends on test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy script
        run: echo "Deploying application..."
